Fix for external DNS resolution
guerzon/vaultwarden pull request #83
Opened 2024-03-23 19:52 UTC by PseudoResonance

Certain setups seem to have trouble with the default ndots:5 dns config. Setting this value to 1 should resolve this.

2024-03-29 03:32 UTC, 0xsanti requested changes

2024-03-29 03:32 UTC, 0xsanti commented on charts/vaultwarden/templates/_podSpec.tpl
> +dnsConfig:
Since we're modifying a default behaviour, I think it's safer if this is an optional value.

2024-03-30 12:21 UTC, PseudoResonance commented
I put it in its own configuration section now for if someone needs to configure anything else with the DNS for whatever reason.

2024-03-30 12:57 UTC, 0xsanti approved these changes

2024-03-30 12:57 UTC, merged